// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaySummary.Models;

namespace PaySummary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220504074437_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("PaySummary.Models.TimeReport", b =>
                {
                    b.Property<int>("TimeReportId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Date");

                    b.Property<int>("EmployeeId");

                    b.Property<decimal>("HoursWorked");

                    b.Property<string>("JobGroup");

                    b.HasKey("TimeReportId");

                    b.ToTable("TimeReports");
                });
#pragma warning restore 612, 618
        }
    }
}
